services:
  user_db:
    image: postgres:17
    container_name: user_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: msa-user
      POSTGRES_USER: msa-user
      POSTGRES_PASSWORD: msa-user
      TZ: UTC
    ports:
      - "54331:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog_db:
    image: postgres:17
    container_name: catalog_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: msa-catalog
      POSTGRES_USER: msa-catalog
      POSTGRES_PASSWORD: msa-catalog
      TZ: UTC
    ports:
      - "54332:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  order_db:
    image: postgres:17
    container_name: order_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: msa-order
      POSTGRES_USER: msa-order
      POSTGRES_PASSWORD: msa-order
      TZ: UTC
    ports:
      - "54333:5432"
    volumes:
      - pgdata3:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  payment_db:
    image: postgres:17
    container_name: payment_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: msa-payment
      POSTGRES_USER: msa-payment
      POSTGRES_PASSWORD: msa-payment
      TZ: UTC
    ports:
      - "54334:5432"
    volumes:
      - pgdata4:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  coupon_db:
    image: postgres:17
    container_name: coupon_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: msa-coupon
      POSTGRES_USER: msa-coupon
      POSTGRES_PASSWORD: msa-coupon
      TZ: UTC
    ports:
      - "54335:5432"
    volumes:
      - pgdata5:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: msa
      RABBITMQ_DEFAULT_PASS: msa
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-master:
    container_name: redis-master
    image: redis:7
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:29092' ## Kafka 수신 리스너 설정
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092' ## 클라이언트에게 노출되는 주소입니다. localhost:29092로 Kafka 접근 가능하게 설정.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT' ## 보안 프로토콜 설정
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "18080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

volumes:
  pgdata1:
  pgdata2:
  pgdata3:
  pgdata4:
  pgdata5:
  rabbitmq_data:
